# 1. Import PyTorch

In [1]:
import torch

# 2. Creating a 1D Tensor


In [16]:
x = torch.Tensor([1,2,3])

In [17]:
x

tensor([1., 2., 3.])

# 3. Accessing an Element in the Tensor


In [18]:
x[2]

tensor(3.)

# 4. Checking the Shape of the Tensor


In [20]:
x.shape

torch.Size([3])

# 5. Element-wise Addition with Another Tensor

In [21]:
x + torch.Tensor([4,4,4])

tensor([5., 6., 7.])

# 6. Adding a Scalar to Each Element

In [7]:
x + 5

tensor([6., 7., 8.])

# 7. Creating a 2D Tensor

In [22]:
x = torch.Tensor([[1,2,3], [4,5,6]])

In [23]:
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [24]:
x[0,1]

tensor(2.)

In [25]:
x + 5

tensor([[ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [28]:
x = torch.randn((1,5))

# Creating a Random Tensor (1x5)

In [29]:
x

tensor([[-2.0062,  0.5842,  1.8769, -0.2862,  0.6655]])

In [14]:
x = torch.randn((2,3))

# Creating Another Random Tensor (2x3)

In [30]:
x

tensor([[-2.0062,  0.5842,  1.8769, -0.2862,  0.6655]])

**Summary**

Tensor Basics: Creating, accessing, and checking shape.

Operations: Addition with scalars and element-wise operations.

Indexing: Accessing specific elements in 1D and 2D tensors.

Random Tensor Generation: Using torch.randn() to create normal-distributed tensors.